version: "3.3"

services:
  webserver:
    build: .
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./database
        target: /database
